version: "3" 
services:
  mysql57:
    container_name: mysql57
    build:
        context: ./mysql57
    restart: always
    volumes:
      #Data folder
      - "./mysql57/data:/var/lib/mysql"
      #Config file
      - "./mysql57/etc:/etc/mysql"
      #Logs folder
      - "./logs/mysql57:/var/log/mysql"
      #Optional host folder
      - "/Users/guilherme/OneDrive/Clientes:/home/Clientes"
      #Logrotate Conf
      - "./logrotate/logrotate.conf:/etc/logrotate.conf"
      - "./logrotate/mysql.conf:/etc/logrotate.d/mysql"
    ports:
      - "3306:3306"
    environment:
      #Root password
      - MYSQL_ROOT_PASSWORD=XXXXXX
      #Additional user/pass without root privilegies (optional)
      - MYSQL_USER=XXXXXX
      - MYSQL_PASSWORD=XXXXXX
    networks:
        - web-server

networks:
    web-server: