version: "3"

services:

    #Apache container
    apache:
        container_name: apache
        build:
            context: ./apache2
        restart: always
        volumes:
            #Document Root folder on your host with your sites
            - "/Users/guilherme/OneDrive/htdocs:/var/www:rw"
            #Log folder
            - "./logs/apache2:/var/log/apache2"
            #Master Apache Conf
            - "./apache2/conf-available/apache2.conf:/usr/local/apache2/conf/httpd.conf:rw"
            #Logrotate Conf
            - "./logrotate/logrotate.conf:/etc/logrotate.conf"
            - "./logrotate/apache2.conf:/etc/logrotate.d/apache2"
        ports:
            - 80:80
            - 8080:8080
            - 443:443
        #Link to PHP containers
        links:
            - php7
            - php56
        #Link to MySQL container
        external_links:
            - mysql57
        depends_on:
            - php7
        networks:
            - web-server
    
    #PHP 7.2 container with FPM
    php7:
        container_name: php7
        restart: always
        build:
            context: ./php7
        volumes:
            #Document Root folder on your host with your sites
            - "/Users/guilherme/OneDrive/htdocs:/var/www:rw"
        ports:
            - 9000:9000
            - 8000:8000
        networks:
            - web-server

    #PHP 5.6 container with FPM
    php56:
        container_name: php56
        restart: always
        build:
            context: ./php56
        volumes:
            #Document Root folder on your host with your sites
            - "/Users/guilherme/OneDrive/htdocs:/var/www:rw"
        ports:
            - 9001:9000
        networks:
            - web-server

networks:
    web-server: